services:

  app:
    build: .
    container_name: retail-app

    ports:
      - "3000:3000"

    environment:
      DB_HOST: retail-db
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: capsule_db

    networks:
      - frontend-network
      - backend-network

    depends_on:
      - database

  database:
    image: mysql:8
    container_name: retail-db

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: capsule_db

    ports:
      - "3306:3306"

    networks:
      - backend-network

    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql

  gateway:
    image: nginx:latest
    container_name: retail-gateway

    ports:
      - "8080:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    networks:
      - frontend-network
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  mysql-data:
